using System.ComponentModel;

namespace EasyTranslate.Enums
{
    public enum TranslateLanguages
    {
        [Description("Afrikaans")] Afrikaans,
        [Description("Albanian")] Albanian,
        [Description("Amharic")] Amharic,
        [Description("Arabic")] Arabic,
        [Description("Armenian")] Armenian,
        [Description("Azerbaijani")] Azerbaijani,
        [Description("Basque")] Basque,
        [Description("Belarusian")] Belarusian,
        [Description("Bengali")] Bengali,
        [Description("Bosnian")] Bosnian,
        [Description("Bulgarian")] Bulgarian,
        [Description("Catalan")] Catalan,
        [Description("Cebuano")] Cebuano,
        [Description("Chichewa")] Chichewa,
        [Description("Chinese (Simplified)")] ChineseSimplified,
        [Description("Chinese (Traditional)")] ChineseTraditional,
        [Description("Corsican")] Corsican,
        [Description("Croatian")] Croatian,
        [Description("Czech")] Czech,
        [Description("Danish")] Danish,
        [Description("Dutch")] Dutch,
        [Description("English")] English,
        [Description("Esperan")] Esperato,
        [Description("Estonia")] Estonan,
        [Description("Filipino")] Filipino,
        [Description("Finnish")] Finnish,
        [Description("French")] French,
        [Description("Frisian")] Frisian,
        [Description("Galician")] Galician,
        [Description("Georgian")] Georgian,
        [Description("German")] German,
        [Description("Greek")] Greek,
        [Description("Gujarati")] Gujarati,
        [Description("Haitian Creole")] HaitianCreole,
        [Description("Hausa")] Hausa,
        [Description("Hawaiian")] Hawaiian,
        [Description("Hebrew")] Hebrew,
        [Description("Hindi")] Hindi,
        [Description("Hmong")] Hmong,
        [Description("Hungarian")] Hungarian,
        [Description("Icelandic")] Icelandic,
        [Description("Igbo")] Igbo,
        [Description("Indonesian")] Indonesian,
        [Description("Irish")] Irish,
        [Description("Italian")] Italian,
        [Description("Japanese")] Japanese,
        [Description("Javanese")] Javanese,
        [Description("Kannada")] Kannada,
        [Description("Kazakh")] Kazakh,
        [Description("Khmer")] Khmer,
        [Description("Korean")] Korean,
        [Description("Kurdish (Kurmanji)")] KurdishKurmanji,
        [Description("Kyrgyz")] Kyrgyz,
        [Description("Lao")] Lao,
        [Description("Latin")] Latin,
        [Description("Latvian")] Latvian,
        [Description("Lithuanian")] Lithuanian,
        [Description("Luxembourgish")] Luxembourgish,
        [Description("Macedonian")] Macedonian,
        [Description("Malagasy")] Malagasy,
        [Description("Malay")] Malay,
        [Description("Malayalam")] Malayalam,
        [Description("Maltese")] Maltese,
        [Description("Maori")] Maori,
        [Description("Marathi")] Marathi,
        [Description("Mongolian")] Mongolian,
        [Description("Mynamar (Burmese)")] MynamarBurmese,
        [Description("Nepali")] Nepali,
        [Description("Norwegian")] Norwegian,
        [Description("Pashto")] Pashto,
        [Description("Persian")] Persian,
        [Description("Polish")] Polish,
        [Description("Portuguese")] Portuguese,
        [Description("Punjabi")] Punjabi,
        [Description("Romanian")] Romanian,
        [Description("Russian")] Russian,
        [Description("Samoan")] Samoan,
        [Description("Scots Gaelic")] ScotsGaelic,
        [Description("Serbian")] Serbian,
        [Description("Sesotho")] Sesotho,
        [Description("Shona")] Shona,
        [Description("Sindhi")] Sindhi,
        [Description("Sinhala")] Sinhala,
        [Description("Slovak")] Slovak,
        [Description("Slovenian")] Slovenian,
        [Description("Somali")] Somali,
        [Description("Spanish")] Spanish,
        [Description("Sundanese")] Sundanese,
        [Description("Swahili")] Swahili,
        [Description("Swedish")] Swedish,
        [Description("Tajik")] Tajik,
        [Description("Tamil")] Tamil,
        [Description("Telugu")] Telugu,
        [Description("Thai")] Thai,
        [Description("Turkish")] Turkish,
        [Description("Ukrainian")] Ukrainian,
        [Description("Urdu")] Urdu,
        [Description("Uzbek")] Uzbek,
        [Description("Vietnamese")] Vietnamese,
        [Description("Welsh")] Welsh,
        [Description("Xhosa")] Xhosa,
        [Description("Yiddish")] Yiddish,
        [Description("Yoruba")] Yoruba,
        [Description("Zulu")] Zulu
    }
}
